
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Fabrício
 */
public class Prato extends javax.swing.JFrame {
  
    private BigDecimal dinheiro;

    public Prato() {
        //descValor.setText("0,00");
        dinheiro = new BigDecimal(BigInteger.ZERO);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        xTudo = new javax.swing.JCheckBox();
        xOvo = new javax.swing.JCheckBox();
        xFrango = new javax.swing.JCheckBox();
        cocaCola = new javax.swing.JCheckBox();
        xCheedar = new javax.swing.JCheckBox();
        coxinha = new javax.swing.JCheckBox();
        extravagante = new javax.swing.JCheckBox();
        bombom = new javax.swing.JCheckBox();
        xBacon = new javax.swing.JCheckBox();
        frangoCatupiry = new javax.swing.JCheckBox();
        fanta = new javax.swing.JCheckBox();
        xSubway = new javax.swing.JCheckBox();
        suco = new javax.swing.JCheckBox();
        quatroQueijo = new javax.swing.JCheckBox();
        pudim = new javax.swing.JCheckBox();
        brigadeiro = new javax.swing.JCheckBox();
        pastel = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        carrinho = new javax.swing.JLabel();
        descValor = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jButton1.setText("Concluir Pedido");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Cardapio Lanchonete");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Laches");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Pizza");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Bebidas");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("Sobremesa");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("Salgadinho");

        xTudo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        xTudo.setText("X-Tudo - R$ 8,90");
        xTudo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xTudoActionPerformed(evt);
            }
        });

        xOvo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        xOvo.setText("X-Ovo - R$ 7,50");
        xOvo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xOvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xOvoActionPerformed(evt);
            }
        });

        xFrango.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        xFrango.setText("X-Frango - R$ 10,00");
        xFrango.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xFrango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xFrangoActionPerformed(evt);
            }
        });

        cocaCola.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cocaCola.setText("Coca-cola - R$ 8,00");
        cocaCola.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cocaCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocaColaActionPerformed(evt);
            }
        });

        xCheedar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        xCheedar.setText("X-Cheedar - R$ 13,50");
        xCheedar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xCheedar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xCheedarActionPerformed(evt);
            }
        });

        coxinha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        coxinha.setText("Coxinha - R$ 3,50");
        coxinha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        coxinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coxinhaActionPerformed(evt);
            }
        });

        extravagante.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        extravagante.setText("Extravagante - R$ 25,00");
        extravagante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        extravagante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extravaganteActionPerformed(evt);
            }
        });

        bombom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bombom.setText("BomBom - R$ 0,75");
        bombom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bombom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bombomActionPerformed(evt);
            }
        });

        xBacon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        xBacon.setText("X-Bacon - R$ 12,60");
        xBacon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xBaconActionPerformed(evt);
            }
        });

        frangoCatupiry.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        frangoCatupiry.setText("Frango/Catupiry - R$ 27,60");
        frangoCatupiry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        frangoCatupiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frangoCatupiryActionPerformed(evt);
            }
        });

        fanta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fanta.setText("Fanta - R$ 6,50");
        fanta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fantaActionPerformed(evt);
            }
        });

        xSubway.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        xSubway.setText("X-Subway - R$ 15,50");
        xSubway.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xSubway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xSubwayActionPerformed(evt);
            }
        });

        suco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        suco.setText("Suco - R$ 5,00");
        suco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        suco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucoActionPerformed(evt);
            }
        });

        quatroQueijo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        quatroQueijo.setText("4 Queijos - R$ 22,50");
        quatroQueijo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quatroQueijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quatroQueijoActionPerformed(evt);
            }
        });

        pudim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pudim.setText("Pudim - R$ 7,60");
        pudim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pudim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pudimActionPerformed(evt);
            }
        });

        brigadeiro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        brigadeiro.setText("Brigadeiro - R$ 1,50");
        brigadeiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        brigadeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brigadeiroActionPerformed(evt);
            }
        });

        pastel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pastel.setText("Pastel - R$ 6,20");
        pastel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pastel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastelActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Carrinho =");

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Valor =");

        carrinho.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        carrinho.setForeground(new java.awt.Color(0, 0, 0));
        carrinho.setText("0");

        descValor.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        descValor.setForeground(new java.awt.Color(0, 0, 0));
        descValor.setText("R$ 0,00");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Concluir Pedido!");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 153));
        jLabel10.setText("Lanchonete");

        jLabel11.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Boa Vista <3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fanta)
                    .addComponent(jLabel4)
                    .addComponent(cocaCola)
                    .addComponent(jLabel1)
                    .addComponent(xTudo)
                    .addComponent(xOvo)
                    .addComponent(xBacon)
                    .addComponent(xCheedar)
                    .addComponent(xSubway)
                    .addComponent(xFrango)
                    .addComponent(suco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(extravagante)
                                .addComponent(quatroQueijo)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(pudim)
                                .addComponent(coxinha)
                                .addComponent(bombom)
                                .addComponent(pastel)
                                .addComponent(brigadeiro))
                            .addGap(15, 15, 15))
                        .addComponent(frangoCatupiry, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel3))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(carrinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(descValor, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel10)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(carrinho)
                            .addComponent(jLabel11))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(descValor))))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addComponent(xTudo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xOvo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xFrango)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xBacon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xCheedar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xSubway)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cocaCola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fanta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(suco))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(extravagante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frangoCatupiry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quatroQueijo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(coxinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pastel)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(brigadeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pudim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bombom)))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xTudoActionPerformed
        if (xTudo.isSelected()) {
            
            dinheiro = dinheiro.add(new BigDecimal("8.90"));
            DecimalFormat df = new DecimalFormat("###,###.00");
            String descDinheiro = df.format(dinheiro);

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) + 1;

            carrinho.setText(itens.toString());

            descValor.setText("R$ " + descDinheiro);
            
        } else {

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) - 1;
            
            dinheiro = dinheiro.subtract(new BigDecimal("8.90"));
            DecimalFormat df = new DecimalFormat("R$ ###,##0.00");
            String descDinheiro = df.format(dinheiro);

            carrinho.setText(itens.toString());

            descValor.setText(descDinheiro);
        }
    }//GEN-LAST:event_xTudoActionPerformed

    private void xOvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xOvoActionPerformed
        if (xOvo.isSelected()) {

            dinheiro = dinheiro.add(new BigDecimal("7.50"));
            DecimalFormat df = new DecimalFormat("###,###.00");
            String descDinheiro = df.format(dinheiro);

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) + 1;

            carrinho.setText(itens.toString());

            descValor.setText("R$ " + descDinheiro);
            
        } else {

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) - 1;
            
            dinheiro = dinheiro.subtract(new BigDecimal("7.50"));
            DecimalFormat df = new DecimalFormat("R$ ###,##0.00");
            String descDinheiro = df.format(dinheiro);

            carrinho.setText(itens.toString());

            descValor.setText(descDinheiro);
        }
    }//GEN-LAST:event_xOvoActionPerformed

    private void xFrangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xFrangoActionPerformed
        if (xFrango.isSelected()) {

            dinheiro = dinheiro.add(new BigDecimal("10.00"));
            DecimalFormat df = new DecimalFormat("###,###.00");
            String descDinheiro = df.format(dinheiro);

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) + 1;

            carrinho.setText(itens.toString());

            descValor.setText("R$ " + descDinheiro);
        } else {

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) - 1;
            
            dinheiro = dinheiro.subtract(new BigDecimal("10.00"));
            DecimalFormat df = new DecimalFormat("R$ ###,##0.00");
            String descDinheiro = df.format(dinheiro);

            carrinho.setText(itens.toString());

            descValor.setText(descDinheiro);
        }
    }//GEN-LAST:event_xFrangoActionPerformed

    private void xBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xBaconActionPerformed
        if (xBacon.isSelected()) {

            dinheiro = dinheiro.add(new BigDecimal("12.60"));
            DecimalFormat df = new DecimalFormat("###,###.00");
            String descDinheiro = df.format(dinheiro);

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) + 1;

            carrinho.setText(itens.toString());

            descValor.setText("R$ " + descDinheiro);
            
        } else {

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) - 1;
            
            dinheiro = dinheiro.subtract(new BigDecimal("12.60"));
            DecimalFormat df = new DecimalFormat("R$ ###,##0.00");
            String descDinheiro = df.format(dinheiro);

            carrinho.setText(itens.toString());

            descValor.setText(descDinheiro);
        }
    }//GEN-LAST:event_xBaconActionPerformed

    private void xCheedarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xCheedarActionPerformed
        if (xCheedar.isSelected()) {

            dinheiro = dinheiro.add(new BigDecimal("13.50"));
            DecimalFormat df = new DecimalFormat("###,###.00");
            String descDinheiro = df.format(dinheiro);

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) + 1;

            carrinho.setText(itens.toString());

            descValor.setText("R$ " + descDinheiro);
            
        } else {

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) - 1;
            
            dinheiro = dinheiro.subtract(new BigDecimal("13.50"));
            DecimalFormat df = new DecimalFormat("R$ ###,##0.00");
            String descDinheiro = df.format(dinheiro);

            carrinho.setText(itens.toString());

            descValor.setText(descDinheiro);
        }
    }//GEN-LAST:event_xCheedarActionPerformed

    private void xSubwayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xSubwayActionPerformed
        if (xSubway.isSelected()) {

            dinheiro = dinheiro.add(new BigDecimal("15.50"));
            DecimalFormat df = new DecimalFormat("###,###.00");
            String descDinheiro = df.format(dinheiro);

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) + 1;

            carrinho.setText(itens.toString());

            descValor.setText("R$ " + descDinheiro);
            
        } else {

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) - 1;
            
            dinheiro = dinheiro.subtract(new BigDecimal("15.50"));
            DecimalFormat df = new DecimalFormat("R$ ###,##0.00");
            String descDinheiro = df.format(dinheiro);

            carrinho.setText(itens.toString());

            descValor.setText(descDinheiro);
        }
    }//GEN-LAST:event_xSubwayActionPerformed

    private void cocaColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocaColaActionPerformed
        if (cocaCola.isSelected()) {

            dinheiro = dinheiro.add(new BigDecimal("8.00"));
            DecimalFormat df = new DecimalFormat("###,###.00");
            String descDinheiro = df.format(dinheiro);

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) + 1;

            carrinho.setText(itens.toString());

            descValor.setText("R$ " + descDinheiro);
            
        } else {

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) - 1;
            
            dinheiro = dinheiro.subtract(new BigDecimal("8.00"));
            DecimalFormat df = new DecimalFormat("R$ ###,##0.00");
            String descDinheiro = df.format(dinheiro);

            carrinho.setText(itens.toString());

            descValor.setText(descDinheiro);
        }
    }//GEN-LAST:event_cocaColaActionPerformed

    private void fantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fantaActionPerformed
        if (fanta.isSelected()) {

            dinheiro = dinheiro.add(new BigDecimal("6.50"));
            DecimalFormat df = new DecimalFormat("###,###.00");
            String descDinheiro = df.format(dinheiro);

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) + 1;

            carrinho.setText(itens.toString());

            descValor.setText("R$ " + descDinheiro);
            
        } else {

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) - 1;
            
            dinheiro = dinheiro.subtract(new BigDecimal("6.50"));
            DecimalFormat df = new DecimalFormat("R$ ###,##0.00");
            String descDinheiro = df.format(dinheiro);

            carrinho.setText(itens.toString());

            descValor.setText(descDinheiro);
        }
    }//GEN-LAST:event_fantaActionPerformed

    private void sucoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucoActionPerformed
        if (suco.isSelected()) {

            dinheiro = dinheiro.add(new BigDecimal("5.00"));
            DecimalFormat df = new DecimalFormat("###,###.00");
            String descDinheiro = df.format(dinheiro);

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) + 1;

            carrinho.setText(itens.toString());

            descValor.setText("R$ " + descDinheiro);
            
        } else {

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) - 1;
            
            dinheiro = dinheiro.subtract(new BigDecimal("5.00"));
            DecimalFormat df = new DecimalFormat("R$ ###,##0.00");
            String descDinheiro = df.format(dinheiro);

            carrinho.setText(itens.toString());

            descValor.setText(descDinheiro);
        }
    }//GEN-LAST:event_sucoActionPerformed

    private void extravaganteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extravaganteActionPerformed
        if (extravagante.isSelected()) {
             
            dinheiro = dinheiro.add(new BigDecimal("25.00"));
            DecimalFormat df = new DecimalFormat("###,###.00");
            String descDinheiro = df.format(dinheiro);

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) + 1;

            carrinho.setText(itens.toString());

            descValor.setText("R$ " + descDinheiro);
            
        } else {

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) - 1;
            
            dinheiro = dinheiro.subtract(new BigDecimal("25.00"));
            DecimalFormat df = new DecimalFormat("R$ ###,##0.00");
            String descDinheiro = df.format(dinheiro);

            carrinho.setText(itens.toString());

            descValor.setText(descDinheiro);
        }
    }//GEN-LAST:event_extravaganteActionPerformed

    private void frangoCatupiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frangoCatupiryActionPerformed
        if (frangoCatupiry.isSelected()) {

            dinheiro = dinheiro.add(new BigDecimal("27.60"));
            DecimalFormat df = new DecimalFormat("###,###.00");
            String descDinheiro = df.format(dinheiro);

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) + 1;

            carrinho.setText(itens.toString());

            descValor.setText("R$ " + descDinheiro);
            
        } else {

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) - 1;
            
            dinheiro = dinheiro.subtract(new BigDecimal("27.60"));
            DecimalFormat df = new DecimalFormat("R$ ###,##0.00");
            String descDinheiro = df.format(dinheiro);

            carrinho.setText(itens.toString());

            descValor.setText(descDinheiro);
        }
    }//GEN-LAST:event_frangoCatupiryActionPerformed

    private void quatroQueijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quatroQueijoActionPerformed
        if (quatroQueijo.isSelected()) {
            
            dinheiro = dinheiro.add(new BigDecimal("22.50"));
            DecimalFormat df = new DecimalFormat("###,###.00");
            String descDinheiro = df.format(dinheiro);

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) + 1;

            carrinho.setText(itens.toString());

            descValor.setText("R$ " + descDinheiro);
            
        } else {

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) - 1;
            
            dinheiro = dinheiro.subtract(new BigDecimal("22.50"));
            DecimalFormat df = new DecimalFormat("R$ ###,##0.00");
            String descDinheiro = df.format(dinheiro);

            carrinho.setText(itens.toString());

            descValor.setText(descDinheiro);
        }
    }//GEN-LAST:event_quatroQueijoActionPerformed

    private void coxinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coxinhaActionPerformed
        if (coxinha.isSelected()) {

            dinheiro = dinheiro.add(new BigDecimal("3.50"));
            DecimalFormat df = new DecimalFormat("###,###.00");
            String descDinheiro = df.format(dinheiro);

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) + 1;

            carrinho.setText(itens.toString());

            descValor.setText("R$ " + descDinheiro);
            
        } else {

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) - 1;
            
            dinheiro = dinheiro.subtract(new BigDecimal("3.50"));
            DecimalFormat df = new DecimalFormat("R$ ###,##0.00");
            String descDinheiro = df.format(dinheiro);

            carrinho.setText(itens.toString());

            descValor.setText(descDinheiro);
        }
    }//GEN-LAST:event_coxinhaActionPerformed

    private void pastelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastelActionPerformed
        if (pastel.isSelected()) {            

            dinheiro = dinheiro.add(new BigDecimal("6.20"));
            DecimalFormat df = new DecimalFormat("###,###.00");
            String descDinheiro = df.format(dinheiro);

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) + 1;

            carrinho.setText(itens.toString());

            descValor.setText("R$ " + descDinheiro);
            
        } else {

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) - 1;
            
            dinheiro = dinheiro.subtract(new BigDecimal("6.20"));
            DecimalFormat df = new DecimalFormat("R$ ###,##0.00");
            String descDinheiro = df.format(dinheiro);

            carrinho.setText(itens.toString());

            descValor.setText(descDinheiro);
        }
    }//GEN-LAST:event_pastelActionPerformed

    private void brigadeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brigadeiroActionPerformed
        if (brigadeiro.isSelected()) {                  

            dinheiro = dinheiro.add(new BigDecimal("1.50"));
            DecimalFormat df = new DecimalFormat("###,###.00");
            String descDinheiro = df.format(dinheiro);

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) + 1;

            carrinho.setText(itens.toString());

            descValor.setText("R$ " + descDinheiro);
            
        } else {

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) - 1;
            
            dinheiro = dinheiro.subtract(new BigDecimal("1.50"));
            DecimalFormat df = new DecimalFormat("R$ ###,##0.00");
            String descDinheiro = df.format(dinheiro);

            carrinho.setText(itens.toString());

            descValor.setText(descDinheiro);
        }
    }//GEN-LAST:event_brigadeiroActionPerformed

    private void pudimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pudimActionPerformed
        if (pudim.isSelected()) {
            
            dinheiro = dinheiro.add(new BigDecimal("7.60"));
            DecimalFormat df = new DecimalFormat("###,###.00");
            String descDinheiro = df.format(dinheiro);

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) + 1;

            carrinho.setText(itens.toString());

            descValor.setText("R$ " + descDinheiro);
            
        } else {

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) - 1;
            
            dinheiro = dinheiro.subtract(new BigDecimal("7.60"));
            DecimalFormat df = new DecimalFormat("R$ ###,##0.00");
            String descDinheiro = df.format(dinheiro);

            carrinho.setText(itens.toString());

            descValor.setText(descDinheiro);
        }
    }//GEN-LAST:event_pudimActionPerformed

    private void bombomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bombomActionPerformed
        if (bombom.isSelected()) {
                              
            dinheiro = dinheiro.add(new BigDecimal("0.75"));
            DecimalFormat df = new DecimalFormat("###,#0.00");
            String descDinheiro = df.format(dinheiro);

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) + 1;

            carrinho.setText(itens.toString());

            descValor.setText("R$ " + descDinheiro);
            
        } else {

            Integer itens = Integer.parseInt(carrinho.getText().trim().equals("") ? "0" : carrinho.getText().trim()) - 1;
            
            dinheiro = dinheiro.subtract(new BigDecimal("0.75"));
            DecimalFormat df = new DecimalFormat("R$ ###,#0.00");
            String descDinheiro = df.format(dinheiro);
            carrinho.setText(itens.toString());

            descValor.setText(descDinheiro);
        }
    }//GEN-LAST:event_bombomActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
               
         if(Integer.parseInt(carrinho.getText())> 0){
             JOptionPane.showMessageDialog(this, "Seu  pedido será entregue no seu endereço!");
             JOptionPane.showMessageDialog(this, "Valor total do pedido: " + descValor.getText());
         }else{
              JOptionPane.showMessageDialog(this, "Selecione seu pedido!");
         }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bombom;
    private javax.swing.JCheckBox brigadeiro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel carrinho;
    private javax.swing.JCheckBox cocaCola;
    private javax.swing.JCheckBox coxinha;
    private javax.swing.JLabel descValor;
    private javax.swing.JCheckBox extravagante;
    private javax.swing.JCheckBox fanta;
    private javax.swing.JCheckBox frangoCatupiry;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JCheckBox pastel;
    private javax.swing.JCheckBox pudim;
    private javax.swing.JCheckBox quatroQueijo;
    private javax.swing.JCheckBox suco;
    private javax.swing.JCheckBox xBacon;
    private javax.swing.JCheckBox xCheedar;
    private javax.swing.JCheckBox xFrango;
    private javax.swing.JCheckBox xOvo;
    private javax.swing.JCheckBox xSubway;
    private javax.swing.JCheckBox xTudo;
    // End of variables declaration//GEN-END:variables
}
